platform :ios,'7.0'

pod "KLCPopup", '~>1.0'
pod 'MJRefresh'
pod 'MBProgressHUD', '~> 0.9.1'
pod "YYCategories"
#pod 'BBBadgeBarButtonItem'
pod 'FMDB'
pod 'iCarousel'
pod 'FXBlurView', '~> 1.6.4'
pod 'UIView+draggable' , '~> 1.1.0'
